### ISSUE TITLE
Ограничения на систему рейтингов

### ISSUE THREAD

**Issue by Elshiko** [K224/party_surfing#104]
придумать и сделать

**Comment by janmak** [comment]
А мне нравится, как сейчас есть: что каждый голосует только по одному разу. Можно ещё добавить ограничение, что за мероприятие можно голосовать только после того, как оно прошло. Хотя с другой стороны, на страницу мероприятия после его окончания могут и не зайти.

**Comment by Elshiko** [comment]
Сейчас можно голосовать за себя, за вписки, к которым не имеешь отношения. Я хочу сделать так: голосовать за прошлые вписки, где ты участник, за людей, которые организовывали вписки, в которых ты участвовал, за людей, с которыми ты участвовал. А ишью я создаю для того, чтобы самому не забыть.

**Comment by duran-duran** [comment]
Не знаю, насколько это оправдано, Сань. У нас же сейчас, как я понимаю, можно с прошедшими мероприятиями что угодно творить: переносить дату на будущее, выкидывать из них участников, выходить участникам собственоручно, вообще отменять.

**Comment by duran-duran** [comment]
Предлагаю просто разрешать оценивать мероприятие только подтвержденным участникам и все. А, ну еще чтобы нельзя было самого себя и свои мероприятия оценивать.

**Comment by alzater** [comment]
Максим - ты должен организовать группу "экспертов" и других членов команды и обсудить, если что-то считаешь нужным делать не так или переделать. А не единолично отдавать рекомендации. Я бы например запретил менять прошедшие мероприятия. А Саня не должен постоянно переделывать свои фичи, потому что у нас разные с тобой мнения. Мы должны все вместе обсудить.

**Comment by diplay** [comment]
Сделано так: 
1.Можно голосовать за всех, кроме себя.
2.Можно голосовать за вписки, в которых ты участвуешь

**Comment by janmak** [comment]
+ #89 Оценка человека
+ #90 Оценка вечеринки

**Comment by janmak** [comment]
Done.
