### ISSUE TITLE
Кнопка "Отменить"

### ISSUE THREAD

**Issue by AnastasiaPetrovskaya** [K224/party_surfing#105]
На странице создания не существует тако кнопки + посмотреть аналогичные кнопки на других страницах.

**Comment by AnastasiaPetrovskaya** [comment]
На странице редактирования кнопка "Отменить" тоже отсутствует

**Comment by duran-duran** [comment]
А зачем отменить, если можно нажать "Назад"?

**Comment by duran-duran** [comment]
А, или это к документации вопрос? Тогда сори.

**Comment by alzater** [comment]
Нужно обсудить. Максим - запиши пожалуйста себе, что бы не забыть завтра обсудить.

**Comment by janmak** [comment]
Из ТЗ удалила, но раз вы решили обсуждать, то не буду закрывать issue
