### ISSUE TITLE
Мероприятие дублируется 

### ISSUE THREAD

**Issue by AnastasiaPetrovskaya** [K224/party_surfing#108]
Скриншот лежит в диалоге вконтакте.
При создании первого мероприятия на странице пользвателя оно отображается два раз

**Comment by duran-duran** [comment]
Хз, у меня не дублируется ничего.

**Comment by AnastasiaPetrovskaya** [comment]
а какая разница, молодец, что у тебя не дуюблируется а я скидывала скриншот в общую группу 
Работать должно всегда, а не через раз

**Comment by diplay** [comment]
а как ты сделала, что у тебя дублируется?
надо воспроизвести хоть как-то, а то не понятно, что исправлять

**Comment by diplay** [comment]
это не баг. там два разных мероприятия
