### ISSUE TITLE
ТЗ (4.1.9 пункт 7: необходимо уточнение)

### ISSUE THREAD

**Issue by AnastasiaPetrovskaya** [K224/party_surfing#109]
4.1.9 пункт 7
Написано что при таких-то обстоятельствах, а что конвкретно при этом не написано, наверно просто забыла дописать

**Comment by duran-duran** [comment]
Насть, в репозитории с документацией насчет ТЗ ишью бы писала лучше, думаю.

**Comment by alzater** [comment]
Думаю, лучше здесь. Что бы все ишью были в одном проекте. Так легче будет отслеживать. И некоторые из них требуют обсуждений. Возможно неточность в ТЗ, а возможно и баг или то что мы забыли доделать.

**Comment by alzater** [comment]
Настя, пиши пожалуйста более подробнее название. Что бы не было подряд несколько одинаковых ишью.

**Comment by janmak** [comment]
Это именно баг ТЗ, я случайно не написала вторую половину предложения. Исправлено.
