### ISSUE TITLE
Нужен дизайн на элементы оценвания

### ISSUE THREAD

**Issue by alzater** [K224/party_surfing#115]
Они уже размещены, но выглядят неочень.

**Comment by janmak** [comment]
Денис, это надо сделать (точно не сделано)

**Comment by Siend** [comment]
Север работает над этим.

**Comment by Siend** [comment]
Все еще жду Севера.

**Comment by janmak** [comment]
Ты его пни, а то времени мало:)

**Comment by Siend** [comment]
пинаю)

**Comment by AnastasiaPetrovskaya** [comment]
разобраться с оцениванием мероприятий

**Comment by AnastasiaPetrovskaya** [comment]
Саша сделал
