### ISSUE TITLE
Проверка ТЗ

### ISSUE THREAD

**Issue by axelhz** [K224/party_surfing#116]
ее, я на гитхабе) 
короче, проверил ТЗ (то, что новое написали), в общем все ок, но
1) нет кнопки отменить и тип-> теги (это уже известно)
2) при проверке email ЕСЛИ ПОСЛЕ @ ЕСТЬ ТОЧКА, НО МЕЖДУ ТОЧКОЙ И @ ИЛИ ПОСЛЕ ТОЧКИ НЕТ БУКВ, ТО ПИШЕТ НЕДОПУСТИМОЕ ПОЛОЖЕНИЕ СИМВОЛА “.”
3) у меня не работает страница редактирования профиля, хз почему (we're sorry, but something went wrong)
4)комментарии на стене могут иметь >2000 символов (например, вписка под названием "вписка у меня")
5) есть грамматические ошибки :)

**Comment by janmak** [comment]
Можешь первый пункт поподробнее?  А то я не поняла:(
