### ISSUE TITLE
Автарки

### ISSUE THREAD

**Issue by AnastasiaPetrovskaya** [K224/party_surfing#118]
При регистрации церес соц-сети необходимо подтягивание фотографий профиля

**Comment by janmak** [comment]
И прочитай сначала, что в ТЗ написано на эту тему:)

**Comment by Elshiko** [comment]
done
Но сейчас они в низком качестве (50х50 вроде), позже поищу как получить получше.
Сейчас приоритет отображения такой: Наша аватарка, аватрка из соц сети, наш плейсхолдер.

Также надо решить вопрос: Если в соц сети нет аватарки, что делать? мне приходит адрес на плейсхолдер соцсети. Нужно ли его скипать, или пусть у нас он отображается?

+ Добавлены 2 кнопки для удаления нашей аватарки и удаления аватарки из соцсети. Нужно решить вопрос необходимости кнопок и в случае чего дизайна и вёрстки.

Также надо проверить все страницы где они есть, что всё работает. Я мог случайно пропустить какое-либо место с ними

**Comment by Elshiko** [comment]
* Мелкие вроде все 100х100
* Большие какие отдали соц сети, те и есть
* Вопрос с плейсхолдером и кнопками висит

**Comment by janmak** [comment]
Записала про фотографии, не закрываю из-за вопроса с плейсхолдерами и кнопками.
