### ISSUE TITLE
Страница всех мероприятий пользователя 

### ISSUE THREAD

**Issue by janmak** [K224/party_surfing#123]
Все мероприятия пользователя на этой странице надо версткой разбить на две колонки / поля:
1. Мероприятия, в которых пользователь участвовал
2. Мероприятия, которые пользователь организовал
и организовать по дате мероприятия (самые новые сверху)
Я могу записывать эту страницу в ТЗ с описанием этих двух полей?

**Comment by alzater** [comment]
Это к дизайнерам и аналитику.

**Comment by alzater** [comment]
Нужны две колонки или два блока друг под другом?

**Comment by duran-duran** [comment]
Тут, конечно, к дизайнерам вопрос, но мне бы представляется, например, два раскрывающихся списка.

**Comment by janmak** [comment]
Зачем раскрывающиеся? Там страница только для мероприятий.

**Comment by duran-duran** [comment]
Один под другим я имею в виду.

**Comment by janmak** [comment]
Совпадает со #98

**Comment by janmak** [comment]
Денис, это надо просто сделать, как написано в самом верху

**Comment by janmak** [comment]
@AnastasiaPetrovskaya может надо, чтобы и на личной странице пользователя мероприятия отображались в этом поле в 2 колонки по тому же принципу?

**Comment by AnastasiaPetrovskaya** [comment]
да, конечно, по -моему нужно

**Comment by Siend** [comment]
С Женей на паре вроде проверяли что это уже реализовано.

**Comment by janmak** [comment]
Нет, я потом смотрела, это именно в тот так радостно сделалось

**Comment by Siend** [comment]
Блин, тогда мне тут помощь левы нужна, у меня на локалке база не заполнена, хрен знает как это проверять. а заполнять ее и каждый раз переключаться - долго будет. + у них там сортировка ж на руби идет. Вообщем пусть лева глянет и отпишится.

**Comment by janmak** [comment]
Ну тогда переведи на него

**Comment by diplay** [comment]
сделал же
