### ISSUE TITLE
Перевод страниц входа и регистрации на русский язык

### ISSUE THREAD

**Issue by alzater** [K224/party_surfing#124]

**Comment by duran-duran** [comment]
Задачу выполнил.

**Comment by janmak** [comment]
![2015-04-10 23 42 29](https://cloud.githubusercontent.com/assets/5188166/7097098/45e0d544-dfdb-11e4-8a76-7c1e0dbfebe0.png)
Может не "Пароли", а "Повторить пароль" или что-нибудь в этом духе?

**Comment by duran-duran** [comment]
Уже поправил это. На хероку только залить надо.
Закрываю тогда.
