### ISSUE TITLE
Валидации для кнопки участвовать

### ISSUE THREAD

**Issue by alzater** [K224/party_surfing#125]
http://party-prototype.herokuapp.com/parties/40
3 раза записался на вписку как участник

**Comment by Elshiko** [comment]
так, а с оцениванием всё ок?

**Comment by duran-duran** [comment]
![grammarnazi](https://cloud.githubusercontent.com/assets/8714437/6873275/31c368e0-d4c0-11e4-8dec-872a294d58e8.png)

**Comment by janmak** [comment]
сошлись со #145 Участие в мероприятие. done
