### ISSUE TITLE
Тестирование целевой аудиторией

### ISSUE THREAD

**Issue by janmak** [K224/party_surfing#129]
Надо попросить попользоваться сервисом и получить фидбек от как можно больше людей из этих 4 категорий:
1. От 18 до 21 года
2. От 22 до 26 лет 
3. От 26 до 30 лет 
4. От 30 до 40 лет (и старше)

Необходим их возраст, пол, общее мнение, проблемы, которые у них возникли и что они хотели бы изменить. Для результатов на гит залит файл Результаты тестирования целевой аудитории. 

Сценарий тестирования для целевой аудитории также залит в папку со всеми документами: Сценарий тестирования целевой аудитории.

**Comment by axelhz** [comment]
сделано
