### ISSUE TITLE
Ошибки для пользователя

### ISSUE THREAD

**Issue by janmak** [K224/party_surfing#132]
Надо протестировать все ошибки, которые выдаются пользователю на совпадение ТЗ. 
+ #131

**Comment by janmak** [comment]
Если при регистрации нового пользователя в поля для адреса электронной почты введен адрес на который уже был зарегистрирован ранее пользователь, то выводится сообщение об ошибке: "Email has already been taken"
#141

**Comment by janmak** [comment]
Проверить в ТЗ наличие сообщения об ошибке при неправильном вводе пароля при входе на сервис

**Comment by AnastasiaPetrovskaya** [comment]
Страница "Редактирование личного профиля" "Name is too long"

**Comment by AnastasiaPetrovskaya** [comment]
Страница создания нового мероприятия , если не введено название мероприятия , то выводится сообщение "Title must not be blank"
