### ISSUE TITLE
Верстка кнопок

### ISSUE THREAD

**Issue by AnastasiaPetrovskaya** [K224/party_surfing#133]
При наведении на кнопки не изменять цвет шрифта, а незначительно изменять цвет копки: чуть сильнее изменять цвет чем сейчас изменяется при наведении на кнопку профиль в шапке сервиса.

**Comment by janmak** [comment]
Кнопка "полный список" на странице мероприятий: убрать фон и ее с большой буквы

**Comment by Siend** [comment]
OK, in proccess

**Comment by Siend** [comment]
![2015-04-10 14 53 08](https://cloud.githubusercontent.com/assets/3957692/7086382/f7ad68a8-df88-11e4-8fee-f2cc74320817.png)
Исправленно.
