### ISSUE TITLE
Страница поиска

### ISSUE THREAD

**Issue by AnastasiaPetrovskaya** [K224/party_surfing#135]
Продумать каким образом можно выводить не все мероприятия в списке справа - например paging  или фильтрация самых популярных мероприятий
Продумать каким образом отображать не все мероприятия на карте - например кластеризация.
Пример реализации кластеризации на сайте http://bus.gov.ru/pub/search/map?searchString=%D1%88%D0%BA%D0%BE%D0%BB%D0%B0

**Comment by duran-duran** [comment]
Пока что ничего не могу сказать по этому вопросу. Обсужу с остальными.

**Comment by duran-duran** [comment]
Поступим так: при поиске по карте будем отображать топ-20 мероприятий по суммарному числу участников и желающих пойти.

**Comment by janmak** [comment]
Добавлено на страницу поиска.
