### ISSUE TITLE
Список мероприятий

### ISSUE THREAD

**Issue by AnastasiaPetrovskaya** [K224/party_surfing#136]
Верстка картинок в списке мероприятий.
Делать обрезку аватарок под нужный формат 
а также для аватарок в комментариях
![image](https://cloud.githubusercontent.com/assets/8748364/6993071/230f0d36-daf1-11e4-8266-acce051564d9.png)
![image](https://cloud.githubusercontent.com/assets/8748364/6993789/beb6f03e-db08-11e4-9a08-b15038840b3f.png)

**Comment by Elshiko** [comment]
Вновь загруженные аватарки будут обрезаться до квадрата, по центру.
Делать редактор по примеру вк нецелесообразно, кого волнует в пэинте обрежут не по центру.

**Comment by Elshiko** [comment]
Большие не теперь не обрезаютс

**Comment by janmak** [comment]
Done.
