### ISSUE TITLE
Страница профиля

### ISSUE THREAD

**Issue by AnastasiaPetrovskaya** [K224/party_surfing#137]
Убрать нижний блок, который под кнопкой Start Surfing
![image](https://cloud.githubusercontent.com/assets/8748364/6993083/7de3b04a-daf1-11e4-8046-5472ab74302f.png)

**Comment by janmak** [comment]
![2015-04-06 12 52 08](https://cloud.githubusercontent.com/assets/5188166/7002988/e49f08e6-dc5b-11e4-8f58-509f39c594ea.png)

Какой-то косяк с отображениями мероприятий

**Comment by Siend** [comment]
Увидел.Требуется помощь Левы. @diplay
