### ISSUE TITLE
Адаптивная верстка

### ISSUE THREAD

**Issue by janmak** [K224/party_surfing#142]
Денис, расскажи мне пожалуйста, для какого количества пикселей и разрешений экранов сделана адаптивная верстка?

**Comment by Siend** [comment]
Очень маленькие устройство Телефоны (<768px)
Малые устройства Планшеты (≥768px)
Средние устройства Настольные (≥992px)
Большие устройства Настольные (≥1200px)

**Comment by janmak** [comment]
И для каждого разный макет?

**Comment by Siend** [comment]
Да нет, только пропорции. ну макет тоже по сути должен отличаться между самым маленьким экраном и остальными, но у нас этого нет)
