### ISSUE TITLE
Регистрация через соцсети

### ISSUE THREAD

**Issue by AnastasiaPetrovskaya** [K224/party_surfing#143]
Если на электронный адрес, на который зарегистрирован аккаунт в социальной сети был зарегистрирован пользователь на сервисе, то при попытке войти через соц сеть должна выводится ошибка желательно : "Email has already been taken"

**Comment by diplay** [comment]
залил на хероку, кто-нибудь проверьте

**Comment by janmak** [comment]
Работает. И для Facebook и просто при регистрации

**Comment by janmak** [comment]
Лева!!!!

**Comment by diplay** [comment]
Что Лева? Ты же сама отписалась, что все работает.

**Comment by janmak** [comment]
На меня не забывай переводить, у меня же в из нет такого сообщения об ошибке
