### ISSUE TITLE
Макеты страниц

### ISSUE THREAD

**Issue by AnastasiaPetrovskaya** [K224/party_surfing#144]
Загрузить на гит новые макеты страниц, только старые не удалять, чтобы они для сравнения остались

**Comment by Siend** [comment]
В каком формате? У меня все макеты в .ai - открывается иллюстратором и фотошопом. Могу конечно как картинки их сделать, если нужно. 
Уточнить.

**Comment by AnastasiaPetrovskaya** [comment]
это было нужно для того чтобы показать, что было и что стало с дизайном в презентации на защите

**Comment by Siend** [comment]
Но я бы честно очень аккуратно показывал это, так как реальность не отвечает ожиданиям)
![1](https://cloud.githubusercontent.com/assets/3957692/7165514/bcd4f940-e3b0-11e4-8a5c-320401d0cb15.jpg)
![2](https://cloud.githubusercontent.com/assets/3957692/7165515/bcf1a1bc-e3b0-11e4-91ed-91f77fabc3f2.jpg)
![3](https://cloud.githubusercontent.com/assets/3957692/7165518/bd0069b8-e3b0-11e4-8ec0-78e61acd3e95.jpg)
![4](https://cloud.githubusercontent.com/assets/3957692/7165517/bcfff8fc-e3b0-11e4-962e-f956fad491ab.jpg)
![5](https://cloud.githubusercontent.com/assets/3957692/7165516/bcffcd1e-e3b0-11e4-9f32-51328586dcdd.jpg)

**Comment by Siend** [comment]
![main-02](https://cloud.githubusercontent.com/assets/3957692/7167213/ff3471a2-e3bb-11e4-8dde-ed3ae47ca6e1.jpg)
