### ISSUE TITLE
Сообщения об ошибках

### ISSUE THREAD

**Issue by AnastasiaPetrovskaya** [K224/party_surfing#146]
Нужно сверить правильность указанных в ТЗ сообщений об ошибках + разработать общую систему сообщений и привести их к единой стилистике - обязательно, чтобы они все были на одном языке, крайне желательно, чтобы они все теперь были составлены на русском языке.

**Comment by duran-duran** [comment]
Временное решение:	
При регистрации:
- Email не введен
- Email уже используется
- Пароль не введен
- Пароль слишком короткий
- Пароли не совпадают
При регистрации/редактировании профиля:
- Дата рождения некорректна
- Имя не должно быть пустым
- Имя слишком длинное
- Фамилия не должна быть пустой
- Фамилия слишком длинная
При редактировании профиля:
- Номер телефона некорректен
При создании мероприятия:
- Местоположение не задано
При создании/редактировании мероприятия:
- Название не должно быть пустым
- Название слишком длинное
- Дата не установлена
- Дата некорректна

**Comment by diplay** [comment]
То, что при регистрации, это ты сам написал? Или это это devise-i18n?

**Comment by duran-duran** [comment]
Короче, пока считаю задачу выполненной.
