### ISSUE TITLE
Верстка рейтинга

### ISSUE THREAD

**Issue by AnastasiaPetrovskaya** [K224/party_surfing#147]
Вместе с Севером решить вопрос верстки блока с рейтингом.
![image](https://cloud.githubusercontent.com/assets/8748364/6993631/fc95b97c-db02-11e4-849b-9ce908451914.png)

**Comment by Siend** [comment]
ПЗДЦ. услышано.

**Comment by Siend** [comment]
Дубляж, уже есть ишью про рейтинг.
