### ISSUE TITLE
Верстка комментариев

### ISSUE THREAD

**Issue by AnastasiaPetrovskaya** [K224/party_surfing#149]
непонятный недоквадратик вокруг аватарки рядом с комментарием пользователя
![image](https://cloud.githubusercontent.com/assets/8748364/6993663/87e53970-db04-11e4-8343-9218b4c93cf1.png)

**Comment by Siend** [comment]
Убрать рамку. Услышано, работаем.

**Comment by Siend** [comment]
![2015-04-09 22 58 20](https://cloud.githubusercontent.com/assets/3957692/7074493/9d6f5e6c-df03-11e4-9856-f5f4976ddfa3.png)
Убрал. Закрываю.
