### ISSUE TITLE
Номер телефона

### ISSUE THREAD

**Issue by AnastasiaPetrovskaya** [K224/party_surfing#153]
В номере телефона можно сохранять не только арабские цифры ,скобки , плюс и  тире
![image](https://cloud.githubusercontent.com/assets/8748364/6996323/d429af98-db89-11e4-92a0-a56a3a79f805.png)
а буквы еще и продублируются в поле город
![image](https://cloud.githubusercontent.com/assets/8748364/6996337/eb00bdf0-db8a-11e4-94b8-1492ab7da89d.png)

**Comment by diplay** [comment]
Там поля город вообще нет в базе, кстати

**Comment by janmak** [comment]
Нет, нету.

**Comment by diplay** [comment]
Ну так что будем делать? Выносить из сайта это поле, или добавлять в базу?

**Comment by janmak** [comment]
Я бы просто убрала поле. Его нигде нет, и у нас пока карта только на Москву настроена
