### ISSUE TITLE
Аватарки на стене

### ISSUE THREAD

**Issue by AnastasiaPetrovskaya** [K224/party_surfing#154]
Когда пользователь оставляет комментарий на странице другого пользователя, рядом с его комментарием отображается не его аватарка , а аватарка того пользователя на чьей странице он оставил комментарий
![image](https://cloud.githubusercontent.com/assets/8748364/6996332/7db02510-db8a-11e4-8d22-c316b408f518.png)

**Comment by Elshiko** [comment]
Вообще было норм, до редизайна. Но несмотря на это, я пофиксил.
