### ISSUE TITLE
Поле контактной информации

### ISSUE THREAD

**Issue by janmak** [K224/party_surfing#155]
![2015-04-05 11 59 36](https://cloud.githubusercontent.com/assets/5188166/6996344/50b22a6c-db8b-11e4-8163-d778acaf061e.png)

Надо его растянуть (может, чтобы оно было одинаковое в полем информацией о себе, может чтобы было 40% поле контактной информации, 60% поле информации о себе. Кроме того, надо как то выделить названия полей (Скайп, Телефон...) и сделать не "Скайп", а "Skype".
Надо сделать дизайн и перевести на Дениса Быконю (Siend).

**Comment by AnastasiaPetrovskaya** [comment]
Лева сделал
