### ISSUE TITLE
Поле "Город"

### ISSUE THREAD

**Issue by AnastasiaPetrovskaya** [K224/party_surfing#156]
При редактировании личной информации есть в личной информации поле "Город", но на странице пользователя оно не отображается никак : 
Нужно ли нам оно? 
Может быть его вообще убрать или отобразить на личной странице?

**Comment by duran-duran** [comment]
Вообще говоря, я считаю, что такое поле сделать стоит. Завтра обсудим.

**Comment by duran-duran** [comment]
Решили убрать это поле. Нужно выпилить из фронтенда
