### ISSUE TITLE
Картинка на главной странице

### ISSUE THREAD

**Issue by janmak** [K224/party_surfing#157]
Надо заменить изображение на главной странице на картинку в более высоком качестве и сделать так, чтобы на любых экранах она растягивалась на весь экран. Вот тут в качестве 2560x1600 http://www.celebrationentertainment.com/images/party-entertainment-in-new-york-3.jpg . Но она немного более темная.

**Comment by Siend** [comment]
Денис считал что это фича, типо чтобы пользователь знал что внизу страницы еще что-то есть.
@AnastasiaPetrovskaya

**Comment by Elshiko** [comment]
http://habrahabr.ru/post/255099/

**Comment by diplay** [comment]
@Elshiko :+1:

**Comment by janmak** [comment]
Надо сделать так, чтобы на всех экранах было более-менее одинаково (а не на одних есть белая полоса, на других нет ее, на третьих кнопка обрезана, на четвертых она полностью). Это от меня и Насти коллективная мысль:)

**Comment by diplay** [comment]
не суть, все умеют скроллить, надо только чтобы большая кнопка была видна всегда. а на картинку насрать

**Comment by Siend** [comment]
@diplay  Лев, глянь плиз. Я с картинкой пофиксил, но там кнопка уезжает почему то ниже чем ей положено, я хз. мб это бустрап себя так ведет? (на маленьком экране проверяй)

**Comment by AnastasiaPetrovskaya** [comment]
Лева сделал
