### ISSUE TITLE
Коментарии

### ISSUE THREAD

**Issue by AnastasiaPetrovskaya** [K224/party_surfing#160]
сверстать комментарии, чтобы не было такой ерунды
#35 тут максим все подробно расписал, а Денис его закрыл ничего не сделав нормально
![image](https://cloud.githubusercontent.com/assets/8748364/6996895/a4f3eb4e-dbac-11e4-8748-384bcbeb974a.png)

**Comment by Siend** [comment]
Наличие бага подтверждаю, ведется работы по исправлению.

**Comment by Siend** [comment]
![2015-04-09 22 44 14](https://cloud.githubusercontent.com/assets/3957692/7074243/a75f7904-df01-11e4-883f-b88c57c9cf5e.png)
Вроде все ок, закрываю.
