### ISSUE TITLE
Сообщения об ошибках

### ISSUE THREAD

**Issue by AnastasiaPetrovskaya** [K224/party_surfing#167]
Остались сообщения  об ошибках на английском языке:
 
![image](https://cloud.githubusercontent.com/assets/8748364/7114255/6aa46764-e1e4-11e4-85fa-b811661df571.png)

**Comment by duran-duran** [comment]
При различных ошибках в написании e-mail'a при регистрации выводится сообщение: "E-mail некорректен"

**Comment by janmak** [comment]
Добавила в ТЗ.
