### ISSUE TITLE
Вставить строчку текста

### ISSUE THREAD

**Issue by janmak** [K224/party_surfing#168]
Надо на странице создания мероприятия вставить строчку текста "Отметьте место проведения мероприятия на карте"

**Comment by diplay** [comment]
C какого хрена?

**Comment by janmak** [comment]
С такого, что это итоги тестирования целевой аудитории. 
Это очень сложно делается?

**Comment by diplay** [comment]
а куда добавить? над картой места нет. сбоку просто написать? не было осуждения.

**Comment by janmak** [comment]
Ну да, в колонке сбоку выбери место и вставь
