### ISSUE TITLE
Кнопки

### ISSUE THREAD

**Issue by AnastasiaPetrovskaya** [K224/party_surfing#169]
Это возможно уже есть, но я не могу найти при наведении на черные кнопки текст не должен становится черным и сливаться с фоном.

**Comment by Siend** [comment]
https://github.com/K224/party_surfing/issues/133

**Comment by Siend** [comment]
Это я вообще то уже исправлял!!! О_О

**Comment by Siend** [comment]
А где именно ты такой косяк нашла?

**Comment by Siend** [comment]
А вижу, на странице просмотра вечеринок. Больше нигде такого не видно было?

**Comment by AnastasiaPetrovskaya** [comment]
да вот хотя бы на любое мероприятие зайти и на кнопку участвовать наведи мышку, во я и удивилась

**Comment by Siend** [comment]
Да, заметил, я видимо только на профиле исправил. щас подкорректирую. а кроме страницы просмотра мероприятий такого нет больше?

**Comment by Siend** [comment]
Все, исправлено. Правда не заливал еще - остальное правлю.
