### ISSUE TITLE
Косяки возникшие при верстке. К разрабам.

### ISSUE THREAD

**Issue by Siend** [K224/party_surfing#26]
1. Поправить центрирвоание на странице входа и регистрации
2. В странице редактирвоания профиля нет обасти для ввода фамилии
3. Если на карте попадешь в панораму - то уже обратно не вернешься
4. На странице вечеринок карта выступает за обозначенную область (не уменьшается)
5. На странице вечеринок, кнопки редактировать, удалить, полный список и участвовать не вставляются в нужные места (либо ошибка, либо плывет вся верстка)
6. Косяк с подтверждением участия в вечеринке. Добавился не желающий а сам автор, а при отказе удалился из участников тоже автор, а не тот кто отказался О_О

**Comment by diplay** [comment]
хз, вроде все норм уже, пусть кто-нибудь еще проверит

**Comment by janmak** [comment]
из этого все:)
