### ISSUE TITLE
Пофиксить поиск по адресу.

### ISSUE THREAD

**Issue by duran-duran** [K224/party_surfing#30]
Насколько я знаю, кнопка "Показать место" на странице поиска функционирует не так, как предполагается. Нужно пофиксить. Кстати, можно как-то сделать выполнение поиска по нажатию Enter? А то как-то совсем странно, вводишь что-то в строку, жмешь энтер и ничего не происходит.

**Comment by diplay** [comment]
#52  - детализированное описание.
