### ISSUE TITLE
Редизайн личного профиля

### ISSUE THREAD

**Issue by duran-duran** [K224/party_surfing#33]
Собственно, нужно сверстать отображение информации в личном профиле (от имени и до комментариев). В частности, надо бы пикчи добавить к полям "Вконтакте" и "Facebook".

**Comment by duran-duran** [comment]
Может, немного дизайна все-таки навесить на личную инфу в профиле? Сделать заголовки, шрифт поюзать там. А то выглядит очень сыро. 
![2](https://cloud.githubusercontent.com/assets/8714437/6318967/2db2d9ac-babc-11e4-94fe-401d44f72228.png)

**Comment by Siend** [comment]
Это вопрос к Северу, какой макет замутите-такой и сделаем)

**Comment by duran-duran** [comment]
Раз уж решили, делаем редизайн личного профиля.
Нужно еще придумать, как будет выглядеть элемент для оценивания.

**Comment by janmak** [comment]
Денис, Лева сказал, что это верстка, можешь посмотреть сделано ли это с соответствие с макетом, и закрыть или сделать:)

**Comment by Siend** [comment]
Сделано.
