### ISSUE TITLE
Верстка комментариев

### ISSUE THREAD

**Issue by duran-duran** [K224/party_surfing#35]
Нужно сверстать отображение комментариев. Можно слизать с ВК, думаю.
Плюс текстовое поле "Оставьте комментарий" нужно растягивающимся сделать, я считаю, а то скроллить написанный текст очень убого.

**Comment by janmak** [comment]
Отсортировать комментарии

**Comment by diplay** [comment]
уже отсортированы

**Comment by duran-duran** [comment]
Не понял, почему ишью закрыли, если кроме сортировки ничего не сделали больше.
Комментарии же не сверстаны вообще.
Опять же, предлагаю сделать textarea для ввода комментариев растягивающейся.

**Comment by diplay** [comment]
так это хз, надо требования, дизайн там и все такое

**Comment by duran-duran** [comment]
Революционный дизайн придумал:
![4](https://cloud.githubusercontent.com/assets/8714437/6319010/1208e9f6-babe-11e4-93e6-cf13f15392b9.png)
Действуй

**Comment by diplay** [comment]
так сейчас почти то же самое

**Comment by duran-duran** [comment]
Так нужно отступы сделать и прочую всячину, чтобы как на пикче не вылазил текст хотя бы.

**Comment by diplay** [comment]
ну тогда перевожу на вертальщика

**Comment by alzater** [comment]
сделано)

**Comment by janmak** [comment]
Я же просила на меня переводить! 😣

**Comment by alzater** [comment]
Думаю, что это относится к схемам. И твоего документирования такая отдельная задача не требует.

**Comment by janmak** [comment]
Не сделано!!!
