### ISSUE TITLE
Отображение мероприятий в личном профиле

### ISSUE THREAD

**Issue by duran-duran** [K224/party_surfing#36]
Имхо, просто блок с название это уж слишком примитивно. Можно или аватарку добавить хотя бы, или поюзать такое же отображение, как в колонке слева от карты на странице поиска.

**Comment by duran-duran** [comment]
В личном профиле для мероприятий, в которых пользователь принимал участие, не отображаются аватарки. Нужно пофиксить.
![4](https://cloud.githubusercontent.com/assets/8714437/6319043/a5ef780a-babf-11e4-92a1-0bb4035d524e.png)

**Comment by Elshiko** [comment]
done
