### ISSUE TITLE
Тип вписки на странице создания/редактирования

### ISSUE THREAD

**Issue by duran-duran** [K224/party_surfing#41]
К #49:
Раз уж с типами пока вопрос нерешенный, может, убрать выбор с этих страниц?

**Comment by diplay** [comment]
раз вопрос нерешенный, то нечего делать пока

**Comment by janmak** [comment]
А у нас есть ограничения на количество тегов или количество символов?

**Comment by duran-duran** [comment]
Нет, но сделать надо бы.

**Comment by diplay** [comment]
Убрать из фронт-енда типы вписок.
