### ISSUE TITLE
аватарки

### ISSUE THREAD

**Issue by Elshiko** [K224/party_surfing#44]
Нужно проверить все места наличия аватарок.
Если нет там, где нужны - пишите.
Цель данного действия - прописать нужные классы картинкам и сверстать.

**Comment by diplay** [comment]
там где в профиле список мероприятий, в которых участвовал и которые создавал, если нажать на аватарку, ничего не происходит. переход только при нажатии на название. может стоит привязать ссылки и к аватаркам тоже? то же самое про аватарки в комментариях

**Comment by Elshiko** [comment]
все аватарки кликабельны
