### ISSUE TITLE
Скрытые поля контактной информации в профиле

### ISSUE THREAD

**Issue by duran-duran** [K224/party_surfing#46]
Косяк в том, что поля скрываются и для самого владельца страницы. Думаю, это нелогично. Нужно поправить так, чтобы они скрывались только для посетителей, но были видны для владельца.

**Comment by duran-duran** [comment]
Вопрос пока отложен до тех времен, как мы будет думать насчет жалоб/черных списков и прочих подобных фишек.

**Comment by diplay** [comment]
Выпилить.

**Comment by janmak** [comment]
Из-за нецелесообразности реализация данной функции отменена.
