### ISSUE TITLE
Закрытые/открытые типы вписок

### ISSUE THREAD

**Issue by janmak** [K224/party_surfing#50]
Разработать и сделать массовую рассылку адреса мероприятия (кнопка на странице мероприятия)

**Comment by diplay** [comment]
тут нужно разработать идею, может не стоит делать сообщения

**Comment by duran-duran** [comment]
Вопрос изначально стоял о закрытых/открытых вписках. Пока отложен на будущее.

**Comment by diplay** [comment]
Дублирует #21. Закрываем.
