### ISSUE TITLE
Полный список гостей

### ISSUE THREAD

**Issue by janmak** [K224/party_surfing#54]
Может придумать хоть какой-то дизайн для это страницы? 

![2015-02-22 13 20 41](https://cloud.githubusercontent.com/assets/5188166/6318204/bb2f3de2-ba95-11e4-8486-7f4f9c6f1e79.png)

**Comment by duran-duran** [comment]
Соответственно, необходимо разработать дизайн.
Собственно, к тому, что сейчас есть я бы добавил разделение всех гостей на два списка:
 - участники (сбоку кнопка отказать)
 - гости/желающие участвовать (сбоку кнопка подтвердить участие)

**Comment by AnastasiaPetrovskaya** [comment]
![guests](https://cloud.githubusercontent.com/assets/8748364/7205654/605249d2-e533-11e4-8ec3-07060a8bec75.png)

**Comment by Siend** [comment]
поправил дизайн кнопки "отклонить/принять", само окно там норм отображается, а программно мы не делим кто хочет а кто точно пойдет. но загрузить не могу, ошибка какая-то жду помощи в вк.
