### ISSUE TITLE
Пофиксить верстку кнопок

### ISSUE THREAD

**Issue by duran-duran** [K224/party_surfing#55]
То, о чем мы в субботу говорили: размер самой ссылки (области, на которую можно клинуть), меньше, чем контейнер.
![1](https://cloud.githubusercontent.com/assets/8714437/6318932/59869386-baba-11e4-9dbd-b4781202fb75.png)
Пока такие косяки нашел на profiles/xxx и parties/yyy.

**Comment by duran-duran** [comment]
Пофиксить можно вроде таким образом: убрать div-контейнер и присвоить bootstrap-класс непосредственно самой ссылке.

**Comment by alzater** [comment]
сделано
