### ISSUE TITLE
Перенос кнопок "Редактировать", "Удалить" на странице мероприятия.

### ISSUE THREAD

**Issue by duran-duran** [K224/party_surfing#56]
![6](https://cloud.githubusercontent.com/assets/8714437/6319099/a9626fb8-bac1-11e4-825c-1d749b815daf.png)
Собственно, я думаю, нужно их перенести под аватар - туда же, где и кнопки "Участвовать"/"Отказаться" для участников. И "удалить"  - плохая формулировка. Можно, например, на "отменить" поменять.

**Comment by diplay** [comment]
тогда надо дизайнер чтобы все поменял, а то у нас опять пойдет несоответствие
пусть переделают все

**Comment by janmak** [comment]
Тогда надо Севера переназначить и написать ему

**Comment by duran-duran** [comment]
Блин, если на каждый чих проходить всю цепочку дизайнер-программист-верстальщик, мы дофига времени потеряем.

**Comment by duran-duran** [comment]
Перекидывайте тогда сами ответственного уж.

**Comment by diplay** [comment]
просто это не доработки, это уже отдельное изменение, которое не входило в изначальный план на неделю

**Comment by alzater** [comment]
давайте без лишней бюрократии. agile как раз и пытается от нее избавиться.
Перенос кнопки - дело не сложное. Сначала перенос, потом либо Север, что-то подправит(цвет, место, размер), либо он одобрит и скинет Жене, что нужно изменить в документах)

**Comment by diplay** [comment]
а смысл переносить? изначально дизайнер решил, что кнопка должна быть там, где она сейчас находится

**Comment by alzater** [comment]
Максим прежде чем создавать эту задачу, должен был обсудить с Севером(нашим экспертом по дизайну). И Север, как ответственный за дизайн, должен был одобрить перенос. После чего мы с тобой должны сделать, а Север поправить недочеты(размер,  цвет и т.д.).
В этом вся суть agile). Не четкая последовательность действий, как вы в инструкции написали, а действия по ситуации. И в каждой ситуации можно собирать разных людей для обсуждения.
А вы начали делать как по ГОСТу: на каждом этапе - ответственный, и каждый хочет побыстрее скинуть основную задачу следующему, что бы избежать ответственности.

**Comment by duran-duran** [comment]
Вот я сейчас открыл макеты дизайнерские, и там вообще нет кнопок редактировать/удалить. Как я понимаю, Денис Быконя просто ткнул их по своему усмотрению. 
А я решил, что нужно хотя бы какой-то унифицированный дизайн иметь, чтобы кнопки в одном месте для гостя/организатора были, и запилил ишью. Хотя согласен, что, согласно методологии, мне надо было бы с Севером это обсудить.

**Comment by duran-duran** [comment]
#92 Более общий вопрос.
