### ISSUE TITLE
Отображение всплывающих окон на карте

### ISSUE THREAD

**Issue by duran-duran** [K224/party_surfing#57]
Во первых, может, стоит сделать так, чтобы при клике на другое мероприятие на карте, окошко с предыдущим закрывалось само?
Во-вторых, нужно подогнать размер самих окошек под содержимое, чтобы не было горизонтального скролла.
![1](https://cloud.githubusercontent.com/assets/8714437/6319150/2ba507a0-bac3-11e4-889a-35f7b3a5762a.png)

**Comment by diplay** [comment]
это баг какой-то, раньше не было

**Comment by diplay** [comment]
там проблема по ходу с шириной дивов внутри окошка, там самопальная верстка от Дениса, так что перекидываю на него

**Comment by janmak** [comment]
Сделано.
