### ISSUE TITLE
АВ страницы создания мероприятия

### ISSUE THREAD

**Issue by alzater** [K224/party_surfing#63]

**Comment by alzater** [comment]
Страница и сейчас на мобиле должна нормально смотреться. Как расположить элементы? оставить ли карту под кнопкой сохранить?

**Comment by alzater** [comment]
небольшие изменения

**Comment by duran-duran** [comment]
Мм, я думаю, это скорее к дизайнерам вопрос. Как по мне, так сейчас как надо выглядит.

**Comment by janmak** [comment]
Макс, ты назначай другого, если говоришь, что не к тебе вопрос. 
Денис, проверь, что АВ сделана, пожалуйста.

**Comment by Siend** [comment]
Собственно она есть - все ресайзится в зависимости от экрана.
