### ISSUE TITLE
Баг востановления пароля

### ISSUE THREAD

**Issue by alzater** [K224/party_surfing#68]
http://party-prototype.herokuapp.com/users/password
при нажатии на кнопку востановить

**Comment by janmak** [comment]
Бэк-енд сделан, но функция не работает, по причине невозможности отсылки писем с нашего хостинга. Переход на другой не целесообразен, так как необходимо предоставить свои финансовые данные, а мы посчитали это нецелесообразным для учебного проекта без финансовой отдачи.
