### ISSUE TITLE
Отображение тегов для найденных мероприятий на странице поиска

### ISSUE THREAD

**Issue by duran-duran** [K224/party_surfing#72]
Нужно запилить, чтобы отображались теги для найденных мероприятий (в колонке слева от карты). Дизайн вроде уже был разработан давно.
![1](https://cloud.githubusercontent.com/assets/8714437/6479601/fe687662-c258-11e4-9f26-ec69aaf408eb.png)

**Comment by diplay** [comment]
теги оторбражаются, пусть теперь верстают

**Comment by janmak** [comment]
Верстка так и не сделана

**Comment by Siend** [comment]
Теги отображаются в общем блоке пати.

**Comment by Siend** [comment]
Блок отображения вечеринок содержит теги. Собственно другого отображения их пока не планируется даже.
