### ISSUE TITLE
Отображение тегов на странице вписки

### ISSUE THREAD

**Issue by duran-duran** [K224/party_surfing#74]
Запилить сабж.
Но прежде, наверное, нужно решить, как это должно выглядеть.

**Comment by diplay** [comment]
отображение есть, теперь нужно запилить дизайн и верстку

**Comment by janmak** [comment]
Проверить наличие верстки и сделать, если ее нет.

**Comment by Siend** [comment]
теги оставляем как есть, норм с ними, ничего лучше ща не придумается
