### ISSUE TITLE
Тип мероприятия

### ISSUE THREAD

**Issue by janmak** [K224/party_surfing#79]
Зачем тип, если он даже не отображается на странице мероприятия? Надо или добавить его на страницы мероприятия, или совсем убрать

**Comment by duran-duran** [comment]
См. #41. Вопросы насчет типов вечеринки мы отложили, т.к. это может быть связано в дальнейшем с монетизацией (введение премиум-акков с возможностью пилить какие-нибудь свои типы мероприятий и т.д.)
