### ISSUE TITLE
Отображение страницы мероприятия для гостя

### ISSUE THREAD

**Issue by janmak** [K224/party_surfing#80]
Почему для гостя на странице мероприятия есть и кнопка "Полный список участников" и отдельные поля "Участники" и "Хотят пойти"? Зачем дублировать? Мне кажется, надо что-то одно оставить.

**Comment by duran-duran** [comment]
Вообще хороший вопрос. Поднимем при случае, не хочу тут дискуссию вести.

**Comment by duran-duran** [comment]
#92 Более общий вопрос.
