### ISSUE TITLE
кнопка Let's party

### ISSUE THREAD

**Issue by AnastasiaPetrovskaya** [K224/party_surfing#84]
не помещается на экране выглядит просто ужасно

**Comment by alzater** [comment]
как именно она должна выглядеть?

**Comment by janmak** [comment]
Зафиксированной снизу

**Comment by alzater** [comment]
Мы с Севером хотели отступы обсудить)

**Comment by janmak** [comment]
Денис, сверстай пожалуйста так, чтобы на любом экране кнопка была чуть-чуть выше низа экрана (Денис Бодунков сказал, что можно просто задать фиксированное количество пикселей)

**Comment by Siend** [comment]
Исправил
![2015-04-10 16 48 40](https://cloud.githubusercontent.com/assets/3957692/7087980/17ec0420-df99-11e4-9186-cb84c4e2fbf5.png)
