### ISSUE TITLE
Оценка человека

### ISSUE THREAD

**Issue by Elshiko** [K224/party_surfing#89]
Сделать возможность поставить оценку профилю пользователя, оценка идёт в зачёт человека как участника

**Comment by Elshiko** [comment]
на странице профиля есть ссылки, чтоб проголосовать, осталось сделать без перезагрузки страницы

**Comment by Elshiko** [comment]
профиль может голосовать за профиль, ограничений нет, голосуй хоть сам за себя. Больше одного голоса нельзя. Удалять оценки свои нельзя.

**Comment by janmak** [comment]
Тоже не смогла найти:(

**Comment by alzater** [comment]
потому что в его ветке

**Comment by Elshiko** [comment]
добавил ajax, смержил

**Comment by janmak** [comment]
![2015-03-18 14 16 11](https://cloud.githubusercontent.com/assets/5188166/6707601/78c8096a-cd79-11e4-999f-4b065d661887.png)
Саш, тут косяк какой то

**Comment by janmak** [comment]
Запишу в ТЗ после добавления ограничений.
