### ISSUE TITLE
Оценка вечеринки

### ISSUE THREAD

**Issue by Elshiko** [K224/party_surfing#90]
Сделать возможность оценить вечеринку, идёт в зачёт человеку в качестве организатора

**Comment by Elshiko** [comment]
можно оценить вечеринку, у вечеринки есть рейтинг, а у профиля есть оценка профиля как организатора, если хоть раз проголосовать, то голос нельзя удалить, ограничений на того, за кого голосовать нет. Если нужны - пирдумаем

**Comment by janmak** [comment]
А ты точно это залил? Я не смогла найти:(

**Comment by Elshiko** [comment]
ну на хероку нет этого, там мастер залит. А я в своей ветке ковыряюсь, завтра попробую доделать полностью и слить.

**Comment by Elshiko** [comment]
теперь добавил

**Comment by janmak** [comment]
Запишу в ТЗ после добавления ограничений.

**Comment by janmak** [comment]
#89
