### ISSUE TITLE
Сделать валидации для тегов

### ISSUE THREAD

**Issue by duran-duran** [K224/party_surfing#93]
Сабж.

**Comment by diplay** [comment]
так в итоге к чему пришли? какая валидация будет?

**Comment by janmak** [comment]
Макс, посмотри, определи какой вариант лучше: ничего не делать, ограничить количество символов или количества тегов, напиши конкретно что делать и кому.

**Comment by duran-duran** [comment]
Предлагаю забить пока на это. Если преподы тыкать не будут, пусть валидации без тегов остаются.

**Comment by janmak** [comment]
А на меня то зачем раз ничего не сделано. @AnastasiaPetrovskaya Насть, посмотри оставлять или нет.

**Comment by duran-duran** [comment]
Сорян, я просто хз, надо это как-то в документации отражать или нет.
