### ISSUE TITLE
Верстка

### ISSUE THREAD

**Issue by janmak** [K224/party_surfing#94]
На всякий случай дублирую то, что написала в ВК:
какой-то косяк с версткой личной страницы: картинки выходят за рамки области и одно мероприятие отличается от других по размеру контура (на этой странице, если что http://party-prototype.herokuapp.com/profiles/10)

**Comment by janmak** [comment]
Денис, страницы по ссылке уже нет (почистили базу), можешь опять таки посмотреть исправлено ли и исправить, если нет.

**Comment by Siend** [comment]
Да вроде норм все, во всяком случае у себя на локальном я проблемы не выявил.
