### ISSUE TITLE
Вход через Facebook

### ISSUE THREAD

**Issue by janmak** [K224/party_surfing#95]
Не работает, он просто делает редирект на главную страницу.

**Comment by diplay** [comment]
Только что проверил. Работает.

**Comment by alzater** [comment]
В каком браузере не работает?

**Comment by janmak** [comment]
Хром. Я же не была авторизована через фейсбук, и он не делает ничего, хотя на самом фейсбуке я все подтвердила

**Comment by alzater** [comment]
посмотрим в субботу

**Comment by janmak** [comment]
Все еще не работает
