### ISSUE TITLE
Страница со всеми мероприятиями пользователя

### ISSUE THREAD

**Issue by alzater** [K224/party_surfing#98]
отобразить все мероприятия, где участвовал и что организовывал.

**Comment by janmak** [comment]
А по какому принципу они сортируются? Просто подряд или на две колонки по принципу где участвовал, и что организовывал?

**Comment by janmak** [comment]
Переверстать на колонки/блоки участвовал и организовал

**Comment by janmak** [comment]
Надо сверстать на две колонки:
1. мероприятия, организованные пользователем
2. мероприятия, в которых участвовал пользователь,
организовать по дате мероприятия (самые недавние сверху)

**Comment by janmak** [comment]
Тоже самое, что и #123.
